// src/app/category/page.tsx
import React, { Suspense } from 'react';
import ProductList from '@/component/ProductList'; // Changed from { ProductList } to ProductList
import Spinner from '@/component/Spinner';

// Metadata for the page
export const metadata = {
  title: 'Category',
  description: 'Generated by create next app',
};
interface CategoryProps {
  params: {
    productid: string;
  }
}


// Server-side async component
export default async function Category({ params }: CategoryProps) {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { productid } = params;
  return (
    <div className="m-5">
      <h1 className="text-4xl mb-5 text-teal-300 font-medium pt-5">
        Our Category
      </h1>
      <p className="text-gray-950 text-lg mb-10">
        Our platform is designed to be user-friendly and secure, ensuring that you can shop with confidence and ease. With reliable customer support, fast shipping, and flexible return policies, we aim to exceed your expectations at every step. Experience the difference with [Your Store Name] — where convenience meets excellence.
      </p>
      <hr className="my-8 border-t border-gray-300" />
      <Suspense fallback={<Spinner />}>
      <ProductList />
      </Suspense>
    </div>
  );
}