import React from 'react'

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  image: string;
}

export default async function Porducts() {
  const response = await fetch('https://fakestoreapi.com/products', {
    cache: 'no-store', // ensures fresh data on every request (SSR)
  });
  const data: Product[] = await response.json();

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">Products</h1>
      <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {data.map((product) => (
          <li key={product.id} className="border rounded p-4 shadow hover:shadow-lg transition">
            <img src={product.image} alt={product.title} className="w-full h-48 object-cover mb-2" />
            <h2 className="text-lg font-semibold">{product.title}</h2>
            <p className="text-sm text-gray-600 line-clamp-2">{product.description}</p>
            <p className="text-blue-600 font-bold mt-2">${product.price}</p>
          </li>
        ))}
      </ul>
    </div>
  );
}
