import React, { Suspense } from 'react';
import Spinner from '@/component/Spinner';
import { fetchProducts } from '@/component/FetchProduct';
import Filter from '@/component/ProductFilter';
import { ProductType } from '@/types/ProductType';

export const metadata = {
  title: 'Products',
  description: 'Generated by create next app',
};

export default async function Products() {
  let products: ProductType[] = [];
  try {
    products = await fetchProducts();
    console.log('Products fetched in page.tsx:', products); // تسجيل البيانات المُجلبة
  } catch (error) {
    console.error('Error fetching products:', error.message);
  }

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-4">Products</h1>
      <Suspense fallback={<Spinner />}>
        <Filter initialProducts={products} />
      </Suspense>
    </div>
  );
}