import React from 'react';


export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function Home() {

  return (
    <div>
      hello
    </div>
  );
}